// <auto-generated />
namespace abw.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDefaultCars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDefaultCars));
        
        string IMigrationMetadata.Id
        {
            get { return "201411041206086_AddDefaultCars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
